CashRewards:
  1:
    - '1000'
    - '2000'
  2:
    - '1000'
    - '2000'
  3:
    - '1000'
    - '2000'
  4:
    - '1000'
    - '2000'
  5:
    - '1000'
    - '2000'
  6:
    - '1000'
    - '2000'
  7:
    - '1000'
    - '2000'
  8:
    - '1000'
    - '2000'
  9:
    - '1000'
    - '2000'
  10:
    - '1000'
    - '2000'
  11:
    - '1000'
    - '2000'
  12:
    - '1000'
    - '2000'
  13:
    - '1000'
    - '2000'
  14:
    - '1000'
    - '2000'
  15:
    - '1000'
    - '2000'
  16:
    - '1000'
    - '2000'
  17:
    - '1000'
    - '2000'
  18:
    - '1000'
    - '2000'
  19:
    - '1000'
    - '2000'
  20:
    - '1000'
    - '2000'
  21:
    - '1000'
    - '2000'
  22:
    - '1000'
    - '2000'
  23:
    - '1000'
    - '2000'
  24:
    - '1000'
    - '2000'
  25:
    - '1000'
    - '2000'
ItemRewards:
  1:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  2:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  3:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  4:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  5:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  6:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  7:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  8:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  9:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  10:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  11:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  12:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  13:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  14:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  15:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  16:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  17:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  18:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  19:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  20:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  21:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  22:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  23:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  24:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'
  25:
    - '1:0'
    - '2:0'
    - '3:0'
    - '4:0'
    - '5:0'
    - '6:0'
    - '7:0'
    - '8:0'
    - '9:0'